// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env first, then let .env.local override it (matches Next.js's own precedence).
loadEnv();
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Roda com o Node puro (type stripping nativo) em vez de tsx: o tsx arrasta o
    // esbuild, cujo binário o EDR desta máquina bloqueia, quebrando o npm install.
    seed: "node --experimental-strip-types prisma/seed.ts",
  },
  datasource: {
    // Migrations run better against Neon's direct (non-pooled) connection;
    // falls back to DATABASE_URL if a separate direct URL isn't provided.
    url: process.env["DIRECT_DATABASE_URL"] || process.env["DATABASE_URL"],
  },
});
